version: "2"

services:
  mongodb:
    image: mongo
    command: mongod
    networks:
      - micro-hotel
  
  reservation:
    build: ./reservation
    networks:
      - micro-hotel
    ports:
      - "1236:8080"
    environment:
       - APP_PORT=8080
       - HOTEL_URL=hotel
       - USER_URL=user
  
  user:
    build: ./user
    networks:
      - micro-hotel
    ports:
      - "1235:8080"
    environment:
       - APP_PORT=8080

  hotel:
    build: ./hotelObject
    networks:
      - micro-hotel
    ports:
      - "1234:8080"
    environment:
       - APP_PORT=8080

  

networks:
  micro-hotel:
    driver: bridge