version: "2"

services:
  app:
    image: golang:1.8
    command: go get github.com/uRevivals/etna-spe-clo5/hotelObject

  mongodb:
    image: mongo
    command: mongod --smallfiles --quiet --logpath=/dev/null