version: "2"

services:
  mongodb:
    image: mongo
    command: mongod
    networks:
      - micro-hotel
  
  app:
    build: .
    networks:
      - micro-hotel
    ports:
      - "1234:1234"

  

networks:
  micro-hotel:
    driver: bridge